name: 'Build AUR Package'
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
  preinstallPkgs:
    description: 'packages need install before build, separated by space'
    required: false
    default: ""
  aur-only:
    description: 'only build package from AUR'
    required: false
    type: boolean
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
